### PR TITLE
Homepage --> HeroSection

### PR DESCRIPTION
**Pull request by ysfdumlu**
push ederken birkaç hata verdi ama hadi bakalım

güncelleme its fixed

### CODE REVIEW

**Comment by ysfdumlu** [comment]
This one is cleanest smoothest code i wrote :)
hero
hero1

**Review by pelinkarakoca — CHANGES_REQUESTED** [review]
Yusuf ellerine sağlık, component looks so good :) There is only a small issue that catches my eye:
- In the figma file, there is two line for the heading: we are here to/ help. In this file "to" is on the other line. maybe, changing text size- 4xl / 9xl will solve the problem

**Comment by ysfdumlu** [comment]
fixed

**Comment by ysfdumlu** [comment]
i add or delete nothing but it looks like same with figma it looks like this in my screen right now
pelin

**Review by akbulatesra — APPROVED** [review]
Thank you, good work

**Review by Hadizios — APPROVED** [review]
love it thanks yusuf ,

**Review by pelinkarakoca — APPROVED** [review]

**Pull request merged**
