### PR TITLE
Hadizios/issue22

### LINKED ISSUE #22: Profile=> Profile info + Profile Thanks
- [x] Full Completion design wise
- [ ]  Mobile Compatibly
- [x]  Test.js
- [x] Connect with firebase

Edit Profile
Edit Thanks

### LINKED ISSUE #38: Counselor => View Info
- [ ] Full completion design wise
- [ ] Mobile compatibility
- [ ] Test.js
- [ ] Connect with Firebase

Screenshot 2023-01-13 at 22 17 09

### PR DESCRIPTION
**Pull request by Hadizios**
Fixes #22

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related Issue
Fixes # (issue)
If suggesting a new feature or change, please discuss it in an issue first

## Screenshots
(prefer animated gif)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally
- [ ] Added tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I've run linter, prettier, and removed all `console.log`
- [ ] I've reverted all the files back that are not related to the issue (App.js, index.js, ...)

### CODE REVIEW

**Comment by Hadizios** [comment]
- mostly finished 
- some mobile responsivness  missing , 
- some functions like " update profile pictures , update docs for some information missing "

**Comment by Nadim-absi** [comment]
Changes made:

- Design slightly altered to fit the rest of the project (pattern etc.)
- Use of components shared between patient and counselor due to similarity
- Addition of multiple thunks with some edits to others to suit the changes made
- Mainly:

1. Paient edit 
2. Counselot edit 
3. Delete user 

Components added: 
image
These contained reusable elements

Pages:
- Edits to profile-edit
- Addition of counselor edit 

**Attention**: 
- Some issues were made with the packeages and yarn.lock, that's why you can see many changes 
- Tests will be added later

To test, please create a new user and try to edit info

**Review by akbulatesra — APPROVED** [review]

**Review by ysfdumlu — APPROVED** [review]
Good work 👍 Thank you

**Review by akbulatesra — APPROVED** [review]
good work thank you

**Pull request merged**
