### PR TITLE
Nadim absi/issue12

### LINKED ISSUE #12: Sign up page=>log in
New feature: the form of the login page
Requirements for this issue:

- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [x]  Test.js

Logical Requirements:

- [ ] Link to sign up page
- [x] Once logged in, website (Navbar) will show user is logged in by showing their name (linked to user slice)

### PR DESCRIPTION
**Pull request by Nadim-absi**
Changes made summary: 

- Addition of Login form component
- Addition of Login Buttons (the Facebook & Google part)
- Adding these changes to Login page

Build changes:
- Use of styled components
- Use of Font Awesome components 

Issue 12 requirements:
- [x] - Mobile Compatibility
- [x] - Design
- [x] Full Tailwind
- [ ] - Testing (half way done)
- [x] - Buttons functionality (Facebbok, google, Signup)
- [x] Error Messages (invalid email/password etc.)

image
image

### CODE REVIEW

**Comment by Nadim-absi** [comment]
Due to issues with Netlify, please don't approve as of yet. They are being worked on.

**Comment by Nadim-absi** [comment]
PR closed as too many changes were made

**Comment by Nadim-absi** [comment]
- Error messages complete
- All buttons work (except sign up, easy to add later)

Testing needs some changes but can change later. Issue completed

**Review by akbulatesra — APPROVED** [review]
great work

**Review by pelinkarakoca — APPROVED** [review]
good work, approved :)

**Pull request merged**
