### PR TITLE
Pelinkarakoca/issue7

### LINKED ISSUE #7: Homepage=> ticket section
New feature: the main Communicate section of the homepage
Requirements for this issue:

- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [x]  Test.js

image

For now the buttons will not link to anything.

### PR DESCRIPTION
**Pull request by pelinkarakoca**

### CODE REVIEW

**Comment by Nadim-absi** [comment]
Great work Pelin but, your branch is not updated to the latest version of the code, which in turn is causing many conflicts. You need to merge main before pushing your code. You can use these steps to fix the problem:

1. git checkout main
2. git pull
3. git checkout <your branch>
4. git merge main
5. Accept all changes
6. git push

Also, please provide a description of the changes you made

**Comment by Nadim-absi** [comment]
Fixed some issues with Netlify.

**Review by Nadim-absi — APPROVED** [review]
Great work, merge approved.

Some changes with width can be done later.

**Comment by pelinkarakoca** [comment]
Current changes: 
- The ticket component is created with three different ticket cards. 
- Screen sizes are arranged as tablets or bigger screens (images can be found in Issue 7).
- Ticket card buttons navigate to the dummy link right now (we can edit it later).

**Comment by Nadim-absi** [comment]
Great changes Pelin.
Approved.

**Review by akbulatesra — APPROVED** [review]
great work, thank you

**Pull request merged**
