### PR TITLE
Hadizios/issue9

### LINKED ISSUE #9: Footer
New feature: the main Footer:
Requirements for this issue:

- [x]  Full Completion design wise
- [ ]  Mobile Compatibly
- [x]  Test.js
- [x] Subscribe must check email validity
- [ ] Subscribe will link to subscribe thanks 

image

### PR DESCRIPTION
**Pull request by Hadizios**

### CODE REVIEW

**Comment by Nadim-absi** [comment]
Great work Hadi but, please provide screenshots of what the final version looks and the changes made

**Comment by Nadim-absi** [comment]
Good work Hadi but, your branch is not updated to the latest version of the code. You have to merge main before pushing your code. Please do the following:
1. git checkout main
2. git pull
3. git checkout <your branch>
4. git merge main 
5. Accept all changes
6. git push 

Also, please provide a description of the changes you made + screenshots

**Comment by Nadim-absi** [comment]
Please make sure all tests are successful before pushing. Some of the tests are failing:
image

**Comment by Nadim-absi** [comment]
Perfect work on pulling main however, you have some problems with the tests. We cannot merge if tests are failing. Some tips to solve them:

1. It should be "data-testid", not "data-testId" (the id is lowercase). Change them in inside the Footer and Subscribe. Also I'm not sure what are the data-sendId and data-inputId are but I don't think you need them. They are causing problems
2. useNavigate will not work (not exactly sure why) but, you can use NavLink instead. Check the Navbar.jsx for an example

**Review by Nadim-absi — APPROVED** [review]
Great Work Hadi!!  Approved.

Changes to responsiveness/bug fixing can be handled later.

**Review by akbulatesra — APPROVED** [review]
Home,Blogs part can be more on the top and right
Subscribe text can be bold 
I just see thats, great work thank you

**Pull request merged**
