### PR TITLE
Akbulatesra/issue23

### PR DESCRIPTION
**Pull request by akbulatesra**
Screen Shot 2023-01-08 at 220051
Screen Shot 2023-01-08 at 220118
Screen Shot 2023-01-08 at 220127

Pages done with responsive design and test files.

### CODE REVIEW

**Review by Hadizios — APPROVED** [review]
amazing , like magic

**Review by pelinkarakoca — APPROVED** [review]
Lol, I couldn't find a better way to describe it than Hadi's :) ellerine sağlık, approved :)

**Review by pelinkarakoca — APPROVED** [review]
approved canım

**Review by Hadizios — APPROVED** [review]
MAGIC !!!

**Review by pelinkarakoca — APPROVED** [review]

**Review by Hadizios — APPROVED** [review]

**Pull request merged**
