### PR TITLE
Pelinkarakoca/issue21

### LINKED ISSUE #21: Contact=> Contact Landing Page + Contact Thanks
- [x] Full Completion design wise
- [ ]  Mobile Compatibly
- [x]  Test.js
- [ ] Connect with firebase

Contact

Contact Thanks

### PR DESCRIPTION
**Pull request by pelinkarakoca**
- There are some issues with mobile compatibility, but I will think about it later (because it needs to be changed for flex I guess)
- Text input gaps will be adjusted
- I didn't connect it with Firebase yet because of the Redux installment

Screenshot 2023-01-19 at 15 40 27

### CODE REVIEW

**Comment by Nadim-absi** [comment]
Great work on the issue, functionality is working as intended. I pushed a commit to resolve conflicts

**Comment by Nadim-absi** [comment]
If possible, try to fix the netlify errors (something related to eslint, you can disable eslint if you want using a commented line). If you find it challenging, you can leave it to me and move on to the next issue. Other than that, great work once again. :)

**Review by ysfdumlu — APPROVED** [review]
It works Thank you

**Review by Nadim-absi — APPROVED** [review]
Great work, thank you

**Pull request merged**
