### PR TITLE
Homepage=>Communicate Section

### LINKED ISSUE #5: Homepage=>Communicate Section
New feature: the main Communicate section of the homepage
Requirements for this issue:

- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [x]  Test.js

image

### PR DESCRIPTION
**Pull request by ysfdumlu**
Fixes #5

### CODE REVIEW

**Comment by pelinkarakoca** [comment]
Good job Yusuf, eline sağlık! But there is an issue with mobile compatibility, we can talk about it at the meeting, then I will approve it :)

**Comment by ysfdumlu** [comment]
smaller screen text overflow(not exposure) fixed with a little cheat.
Tried HOURSSSS this is what i can do about this problem :) Its actually fixed. Could you review again
Thanks

**Review by pelinkarakoca — APPROVED** [review]
Good job, approved

**Review by Hadizios — APPROVED** [review]
great work Yusuf ,  approved  

notes for future testing , 
- adding padding for text section ,  checking responsiveness  to be aligned with other components in homepage .

**Review by pelinkarakoca — APPROVED** [review]
Thank you both of you, approved

**Review by Hadizios — APPROVED** [review]
great work yusuf

**Pull request merged**
