### PR TITLE
Nadim absi/issue37

### LINKED ISSUE #37: Counselor=> Therapist Create + Therapist Thanks
- [x]  Full Completion design wise
- [x]  Mobile Compatibly
- [ ] Test.js
- [x] Connect with firebase

Screenshot 2023-01-13 at 22 15 00
Screenshot 2023-01-13 at 22 15 51

### PR DESCRIPTION
**Pull request by Nadim-absi**
This pull request configures the counselor create section. 

### **Design Deliverables:**
- Created the counsellor signup form
- Created the counsellor signup thanks page
- All designs made to be mobile compatible

### **Technical Deliverables:**
- Counsellor signup would create a user on **authentication**
- Counsellor signup would create a document in **counsellors** collection with the same **uid**
- All logic is similar to normal sign up
- Login logic unchanged
- **currentUserHandler** will now also check the counsellors collection

Designs:
image
image
image
image

### CODE REVIEW

**Comment by Nadim-absi** [comment]
**NOTE**:  only merge after #46.

**Comment by akbulatesra** [comment]
Google and Facebook Signup and Login Parts not working, other than  awesome work thank you.

**Review by akbulatesra — APPROVED** [review]

**Comment by Nadim-absi** [comment]
The facebook/google parts issue has been identified. Will try to fix the problem as soon as possible.

**Comment by Nadim-absi** [comment]
Facebook/Google issue on netlify has been fixed.

**Comment by ysfdumlu** [comment]
If something needs to happen when you press the create button on the registration page, nothing happens when you press it.
(i will approve this if there is something wrong we will handle later)
All other things work Good job thank you.

**Review by ysfdumlu — APPROVED** [review]
If something needs to happen when you press the create button on the registration page, nothing happens when you press it.
(i will approve this if there is something wrong we will handle later)
All other things work Good job thank you.

**Review by ysfdumlu — APPROVED** [review]

**Review by akbulatesra — APPROVED** [review]

**Pull request merged**
