### PR TITLE
Pelinkarakoca/issue36

### LINKED ISSUE #36: Blogs => Blog Slider
- [x] Full completion design wise 
- [x] Mobile compability
- [ ] Test.js
- [ ] Connect with firebase and redux
- [x] Add blog routes

Screenshot 2023-01-13 at 22 07 49

### PR DESCRIPTION
**Pull request by pelinkarakoca**
COMPLETED:
- Full design 
- Functionality
-
ATTENTION:
- The blog component is finished without margins. 
- Test gives errors!

### CODE REVIEW

**Review by Nadim-absi — CHANGES_REQUESTED** [review]
Great work on the functionality but, I think there's a problem with the widths/height maybe?? Because the main image is too large and taking up the entire screen.

**Review by akbulatesra — COMMENTED** [review]
would you add padding right and left and the main image can be smaller. Others are great thank you :)

**Review by akbulatesra — APPROVED** [review]
as always great work <3

**Review by Nadim-absi — APPROVED** [review]
we should always listent to esra , great work

**Pull request merged**
