### PR TITLE
issue4 completed

### LINKED ISSUE #4: Homepage=> Yellow Section
New feature: the main Hero section of the homepage 
Requirements for this issue:

- [x] Full Completion design wise
- [x] Mobile Compatibly
- [x] Test.js

image

### PR DESCRIPTION
**Pull request by ysfdumlu**
there is 3 checkbox in this issue and all of it filled
yellowsec

### CODE REVIEW

**Comment by Nadim-absi** [comment]
The design is good but some things need fixing:

1. Try to decease the height a bit (too large)
2. Mobile compatibility needs fixing

**Comment by ysfdumlu** [comment]
Fixed mobile compatibility and hight problem can you review again
Thanks

**Comment by ysfdumlu** [comment]
There is a odd situation about image(therapist profile picture) when screen shrinking but not that much important i guess i could not fix it properly but it still works in a awkward way

**Review by akbulatesra — APPROVED** [review]
Great work, thank you

**Comment by ysfdumlu** [comment]
adjusted a bit about text overflow the border it works now at all widths of 272 pixels and above but same problem occur if screen goes under 272px width but i think there is no screen below it so i chose to move on

**Review by Nadim-absi — APPROVED** [review]
Perfect Work,  Approve

**Pull request merged**
